FROM mcr.microsoft.com/playwright/python:v1.54.0-noble

WORKDIR usr/src/app

RUN apt-get update && apt-get install -y bash

COPY src/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x scripts/run_playwright_tests.sh

RUN playwright install --with-deps

CMD ["pytest", "tests/"]

