FROM mcr.microsoft.com/playwright/python:v1.54.0-noble

WORKDIR usr/src/app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN playwright install --with-deps

CMD ["pytest", "tests/"]

